###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: baseauth-service-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    ##url: jdbc:mysql://localhost:3306/pms_new?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/pms_new?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: pms_new
    password: pms_new
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      initial-size: 5
##mybatis
mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.baseauth.system.model
#############服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
